spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mycommunity?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: jsbbsj
    username: root

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml